version: "3.9"
volumes:
  postgres: {}
services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_DB: sqlstmt_dev
      POSTGRES_USER: sqlstmt
      POSTGRES_PASSWORD: sqlstmt
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  migrate:
    depends_on:
      - postgres
    image: migrate/migrate:4
    volumes:
      - ./migrations:/data/migrations
